namespace Ae.Engine
{
    /// <summary>
    /// Specifies the logging levels available for application event logging.
    /// </summary>
    /// <remarks>Use this enumeration to control the verbosity and severity of log messages generated by the
    /// application. The levels range from detailed diagnostic output to error reporting. Selecting an appropriate
    /// logging level helps filter log output and manage log storage effectively.</remarks>
    public enum AeLoggingLevel
    {
        /// <summary>
        /// Verbose status messages.
        /// </summary>
        Verbose,
        /// <summary>
        /// General status messages.
        /// </summary>
        Information,
        /// <summary>
        /// Something the user might want to be aware of.
        /// </summary>
        Warning,
        /// <summary>
        /// An actual exception has been thrown.
        /// </summary>
        Error
    }

    /// <summary>
    /// Specifies the types of assets supported by the engine.
    /// </summary>
    public enum AeBaseAssetType
    {
        /// <summary>
        /// Text types, such as JSON, XML, or plain text files.
        /// </summary>
        Text,
        /// <summary>
        /// C# code files.
        /// </summary>
        Code,
        /// <summary>
        /// Wave sound files.
        /// </summary>
        Sound,
        /// <summary>
        /// Images, typically used as sprites.
        /// </summary>
        Image
    }

    /// <summary>
    /// Specifies the types of nodes that are added to the editor tree.
    /// </summary>
    public enum AeCodeType
    {
        /// <summary>
        /// Plain text.
        /// </summary>
        Text,
        /// <summary>
        /// C# code.
        /// </summary>
        CSharp,
        /// <summary>
        /// Json data.
        /// </summary>
        JSON,
        /// <summary>
        /// XML document.
        /// </summary>
        XML,
        /// <summary>
        /// Markdown document (used for documentation assets).
        /// </summary>
        MarkDown
    }

    /// <summary>
    /// Specifies the group that the property belongs to in the property editor.
    /// This is used to group properties together in the UI and can be used for organizational purposes.
    /// </summary>
    public enum AePropertyEditorGroup
    {
        /// <summary>
        /// General properties that apply to most/all assets.
        /// </summary>
        Base,
        /// <summary>
        /// Properties for attachment assets.
        /// </summary>
        Attachment,
        /// <summary>
        /// Destruction related properties, such as explosion effects, debris, and other visual/audio effects that occur when an object is destroyed.
        /// </summary>
        Destroy,
        /// <summary>
        /// Health related properties, such as hit points, shields, and other attributes that determine an object's survivability and response to damage.
        /// </summary>
        Health,
        /// <summary>
        /// Collision related properties, such as hitboxes, collision damage, and other attributes that determine how an object interacts with other objects in terms of physical collisions.
        /// </summary>
        Collision,
        /// <summary>
        /// Momentum related properties, such as speed, acceleration, and other attributes that determine how an object moves and responds to forces in the game world.
        /// </summary>
        Momentum,
        /// <summary>
        /// Animation  related properties, such as animation frames, frame rate, and other attributes that determine how an object's visual representation changes over time to create the illusion of movement or transformation.
        /// </summary>
        Animation,
        /// <summary>
        /// Weapons related properties, such as weapon types, firing rates, and other attributes that determine how an object can attack or interact offensively with other objects in the game world.
        /// </summary>
        Weapons,
        /// <summary>
        /// Munition related properties, such as munition types, damage, and other attributes that determine how projectiles or other offensive effects behave when fired from a weapon or attachment.
        /// </summary>
        Munitions,
        /// <summary>
        /// Artificial intelligence related properties, such as behavior patterns, decision-making parameters, and other attributes that determine how non-player characters (NPCs) or other autonomous entities behave and interact within the game world.
        /// </summary>
        AI,
        /// <summary>
        /// Audio related properties, such as sound effects, music, and other attributes that determine how an object produces or interacts with sound in the game world.
        /// </summary>
        Audio
    }

    /// <summary>
    /// Editor types for properties in the property editor. This determines how a property is displayed and edited in the UI.
    /// </summary>
    public enum AePropertyEditorType
    {
        /// <summary>
        /// Can not be altered.
        /// </summary>
        Readonly,
        /// <summary>
        /// A single line string.
        /// </summary>
        String,
        /// <summary>
        /// Multi-line string.
        /// </summary>
        Text,
        /// <summary>
        /// Integer value.
        /// </summary>
        Integer,
        /// <summary>
        /// Floating point value.
        /// </summary>
        Float,
        /// <summary>
        /// Boolean value.
        /// </summary>
        Boolean,
        /// <summary>
        /// Range of integer values, with a specified minimum and maximum.
        /// </summary>
        RangeInt,
        /// <summary>
        /// Range of floating point values, with a specified minimum and maximum.
        /// </summary>
        RangeFloat,
        /// <summary>
        /// Represents a mathematical vector with components in one or more dimensions.
        /// </summary>
        Vector,
        /// <summary>
        /// Can pick a class from the enumerated list of that have the AssetClassAttribute.
        /// </summary>
        Class,
        /// <summary>
        /// Values from an enum type will be displayed as options.
        /// </summary>
        Enum,
        /// <summary>
        /// Values from a pre-defined list will be displayed as options.
        /// </summary>
        Picker,
        /// <summary>
        /// Can select multiple sprites.
        /// </summary>
        MultipleSpritePicker,
        /// <summary>
        /// Can select a single sprite.
        /// </summary>
        SingleSpritePicker
    }

    /// <summary>
    /// Represent a rotation direction.
    /// </summary>
    public enum AeRotationDirection
    {
        /// <summary>
        /// Unspecified or undefined.
        /// </summary>
        None,
        /// <summary>
        /// Rotate in the direction of a clock's hands (to the right).
        /// </summary>
        Clockwise,
        /// <summary>
        /// Rotate in the opposite direction of a clock's hands (to the left).
        /// </summary>
        CounterClockwise
    }

    /// <summary>
    /// Determines the behavior of a attachment sprite's position.
    /// </summary>
    public enum AeAttachmentPositionType
    {
        /// <summary>
        /// The attached sprite's position will automatically stay at a fixed position on the owner sprite, even when the owner moves and rotates.
        /// Managed in ApplyMotion().
        /// </summary>
        FixedToOwner,

        /// <summary>
        /// The attached sprite's position will not be automatically managed by ApplyMotion().
        /// </summary>
        Independent
    }

    /// <summary>
    /// Specifies the available explosion types for fire and energy effects.
    /// </summary>
    public enum AeExplosionType
    {
        /// <summary>
        /// A medium sized explosion with fire suitable for explosion damage effects.
        /// </summary>
        MediumFire,
        /// <summary>
        /// A large sized explosion with fire suitable for explosion effects.
        /// </summary>
        LargeFire,
        /// <summary>
        /// A medium sized explosion with fire suitable for moderate damage effects.
        /// </summary>
        SmallFire,
        /// <summary>
        /// A medium sized explosion with fire suitable for damage effects.
        /// </summary>
        MicroFire,
        /// <summary>
        /// A medium sized explosion with the appearance of plasma suitable for explosion effects.
        /// </summary>
        Energy
    }

    /// <summary>
    /// Determines the behavior of a attachment sprite's orientation.
    /// </summary>
    public enum AeAttachmentOrientationType
    {
        /// <summary>
        /// The attached sprite should always face the direction of the owner sprite. Managed in ApplyMotion().
        /// </summary>
        FixedToOwner,

        /// <summary>
        /// The attached sprite's orientation will not be automatically managed by ApplyMotion().
        /// </summary>
        Independent
    }

    /// <summary>
    /// Specifies the execution mode for the engine instance.
    /// </summary>
    /// <remarks>Use this enumeration to indicate whether the engine is running in play, edit, server host, or
    /// shared content mode. The execution mode determines how the engine behaves and interacts with levels and
    /// multiplayer scenarios.</remarks>
    public enum AeEngineExecutionMode
    {
        /// <summary>
        /// Execution mode is not yet determined or does not apply to the current context.
        /// </summary>
        None,
        /// <summary>
        /// User play more
        /// </summary>
        Play,
        /// <summary>
        /// User edit mode.
        /// </summary>
        Edit,
        /// <summary>
        /// The engine instance is intended to run a level on the server for multiplayer games.
        /// </summary>
        ServerHost,
        /// <summary>
        /// This engine instance is intended to be shared content only, not to run a level.
        /// </summary>
        SharedEngineContent
    }

    /// <summary>
    /// Represents the type of lock applied to a weapon, determining how it can be used or switched.
    /// </summary>
    public enum AeWeaponsLockType
    {
        /// <summary>
        /// Not locked.
        /// </summary>
        None,
        /// <summary>
        /// Locked on.
        /// </summary>
        Hard,
        /// <summary>
        /// Not locked, but in range for a valid lock.
        /// </summary>
        Soft
    }

    /// <summary>
    /// Represents the cleanup mode for particles, determining how and when they should be removed from the game world.
    /// </summary>
    public enum AeParticleCleanupMode
    {
        /// <summary>
        /// Do not remove.
        /// </summary>
        None,
        /// <summary>
        /// Particles get removed when they fade to black (when their color is fully black and they are no longer visible on the screen).
        /// </summary>
        FadeToBlack,
        /// <summary>
        /// Particles are removed when they are a certain distance off the screen, even if they are still visible (for example, if they are large and extend off the screen).
        /// </summary>
        DistanceOffScreen
    }

    /// <summary>
    /// Represents the shape of a particle, determining how it is rendered on the screen.
    /// </summary>
    public enum AeParticleShape
    {
        /// <summary>
        /// A filled ellipse.
        /// </summary>
        FilledEllipse,
        /// <summary>
        /// A hollow ellipse.
        /// </summary>
        HollowEllipse,
        /// <summary>
        /// A hollow rectangle.
        /// </summary>
        HollowRectangle,
        /// <summary>
        /// A filled rectangle.
        /// </summary>
        FilledRectangle,
        /// <summary>
        /// A triangle.
        /// </summary>
        Triangle
    }

    /// <summary>
    /// Represents the color type of a particle.
    /// </summary>
    public enum AeParticleColorType
    {
        /// <summary>
        /// Single solid color.
        /// </summary>
        Solid,
        /// <summary>
        /// Color gradient.
        /// </summary>
        Gradient
    }

    /// <summary>
    /// Represents the vector type of a particle, determining how its movement direction is calculated.
    /// </summary>
    public enum AeParticleVectorType
    {
        /// <summary>
        /// The sprite will travel in the direction determined by it's MovementVector.
        /// </summary>
        Default,
        /// <summary>
        /// The sprite will travel in the direction in which is is oriented.
        /// </summary>
        FollowOrientation
    }

    /// <summary>
    /// Specifies the order in which a sprite is rendered relative to screen scaling based on speed.
    /// </summary>
    /// <remarks>Use this enumeration to control whether a sprite is affected by screen scaling. Selecting
    /// PreScale renders the sprite before scaling, causing it to be scaled along with the screen. Selecting PostScale
    /// renders the sprite after scaling, so it is not affected by the screen scale.</remarks>
    public enum AeRenderScaleOrder
    {
        /// <summary>
        /// Render this sprite before scaling the screen based on speed (the sprite will be scaled).
        /// </summary>
        PreScale,
        /// <summary>
        /// Render this sprite after scaling the screen based on speed (the sprite will not be scaled).
        /// </summary>
        PostScale
    }

    /// <summary>
    /// Represents the state of a level, indicating whether it has not yet started, is currently in progress, or has ended.
    /// </summary>
    public enum AeLevelState
    {
        /// <summary>
        /// Not yet started.
        /// </summary>
        NotYetStarted,
        /// <summary>
        /// Started and running,
        /// </summary>
        Started,
        /// <summary>
        /// Ended.
        /// </summary>
        Ended
    }


    /// <summary>
    /// Represents the state of a situation, indicating whether it has not yet started, is currently in progress, or has ended.
    /// </summary>
    public enum AeSituationState
    {
        /// <summary>
        /// Not yet started.
        /// </summary>
        NotYetStarted,
        /// <summary>
        /// Started and running,
        /// </summary>
        Started,
        /// <summary>
        /// Ended.
        /// </summary>
        Ended
    }

    /// <summary>
    /// Specifies the cardinal directions used for navigation or orientation.
    /// </summary>
    /// <remarks>This enumeration includes the four primary compass directions and a value representing no
    /// direction. It can be used to indicate orientation, movement, or positioning in applications such as mapping,
    /// gaming, or robotics.</remarks>
    public enum AeCardinalDirection
    {
        /// <summary>
        /// Undefined direction.
        /// </summary>
        None,
        /// <summary>
        /// North.
        /// </summary>
        North,
        /// <summary>
        /// East.
        /// </summary>
        East,
        /// <summary>
        /// South.
        /// </summary>
        South,
        /// <summary>
        /// West.
        /// </summary>
        West
    }

    /// <summary>
    /// Represents the type of a menu item in the user interface, determining how it is displayed and interacted with.
    /// </summary>
    public enum AeMenuItemType
    {
        /// <summary>
        /// Undefined or default menu item type, which may be used as a placeholder or when the type is not specified.
        /// </summary>
        Undefined,
        /// <summary>
        /// Title menu item, typically used for headings or section titles in the menu.
        /// </summary>
        Title,
        /// <summary>
        /// Simple text block.
        /// </summary>
        TextBlock,
        /// <summary>
        /// Selectable text item that can be highlighted and selected by the user, often used for interactive menu options or buttons.
        /// </summary>
        SelectableItem,
        /// <summary>
        /// Selectable text item that can be highlighted and selected by the user, and also allows for user input, such as entering text or numbers.
        /// </summary>
        SelectableTextInput
    }

    /// <summary>
    /// Defines the play mode of an animation.
    /// </summary>
    public enum AeAnimationPlayMode
    {
        /// <summary>
        /// The animation will be played once and can be replayed by calling Play().
        /// </summary>
        Single,
        /// <summary>
        /// The animation will be played once then will be deleted.
        /// </summary>
        DeleteAfterPlay,
        /// <summary>
        /// The animation will loop until manually deleted or hidden.
        /// </summary>
        Infinite
    };

    /// <summary>
    /// Defines the type of damage being applied to a sprite, which can affect how the damage is processed and how the sprite responds to it.
    /// </summary>
    public enum AeDamageType
    {
        /// <summary>
        /// Undefined.
        /// </summary>
        Unspecified,
        /// <summary>
        /// Damage to the shield.
        /// </summary>
        Shield,
        /// <summary>
        /// Damage to the hull.
        /// </summary>
        Hull
    }

    /// <summary>
    /// Specifies the source type from which an action event was fired.
    /// </summary>
    /// <remarks>Use this enumeration to distinguish whether an event originated from a player, an enemy, or
    /// is unspecified. This can be useful for handling game logic based on the event source.</remarks>
    public enum AeFiredFromType
    {
        /// <summary>
        /// Unknown or invalid.
        /// </summary>
        Unspecified,
        /// <summary>
        /// Fired from a player-controlled entity.
        /// </summary>
        Player,
        /// <summary>
        /// Fired from a non-player enemy entity.
        /// </summary>
        Enemy
    }

    /// <summary>
    /// Defines the keys used for player input, which can be mapped to specific actions or controls in the game.
    /// </summary>
    public enum AePlayerKey
    {
        /// <summary>
        /// Switches the currently equipped weapon to the previous weapon in the inventory.
        /// </summary>
        SwitchWeaponLeft,
        /// <summary>
        /// Switches to the next weapon in the available weapon list.
        /// </summary>
        SwitchWeaponRight,
        /// <summary>
        /// Moves the entity to the right relative to its current orientation.
        /// </summary>
        StrafeRight,
        /// <summary>
        /// Moves the entity to the left relative to its current orientation.
        /// </summary>
        StrafeLeft,
        /// <summary>
        /// Speed boost key.
        /// </summary>
        SpeedBoost,
        /// <summary>
        /// Forward movement key, which moves the entity in the direction it is currently facing.
        /// </summary>
        Forward,
        /// <summary>
        /// Reverse movement key, which moves the entity in the opposite direction it is currently facing.
        /// </summary>
        Reverse,
        /// <summary>
        /// Fire primary weapon.
        /// </summary>
        PrimaryFire,
        /// <summary>
        /// Fire selected secondary weapon.
        /// </summary>
        SecondaryFire,
        /// <summary>
        /// Rotate counterclockwise, which rotates the entity to the left.
        /// </summary>
        RotateCounterClockwise,
        /// <summary>
        /// Rotate clockwise, which rotates the entity to the right.
        /// </summary>
        RotateClockwise,
        /// <summary>
        /// Escape key, exit or show menu.
        /// </summary>
        Escape,
        /// <summary>
        /// Left selection key, used for menu navigation or other interactions.
        /// </summary>
        Left,
        /// <summary>
        /// Right selection key, used for menu navigation or other interactions.
        /// </summary>
        Right,
        /// <summary>
        /// Up selection key, used for menu navigation or other interactions.
        /// </summary>
        Up,
        /// <summary>
        /// Down selection key, used for menu navigation or other interactions.
        /// </summary>
        Down,
        /// <summary>
        /// Enter selection key, used confirming menu selections.
        /// </summary>
        Enter
    }
}
