<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Title>Axis Engine</Title>
		<Company>NetworkDLS</Company>
		<Copyright>Copyright © 2026 NetworkDLS</Copyright>
		<Version>0.0.46</Version>
		<Authors>NetworkDLS</Authors>

		<Nullable>enable</Nullable>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<AssemblyName>Ae.MpCommsMessages</AssemblyName>
		<RootNamespace>Ae.MpCommsMessages</RootNamespace>
		<ApplicationIcon>AeIcon.ico</ApplicationIcon>

		<TargetFrameworks></TargetFrameworks>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Description>
			Axis Engine is a 2D game engine written in C# and rendered with DirectX.
		</Description>
		<PackageProjectUrl>https://github.com/NTDLS/AxisEngine</PackageProjectUrl>
		<RepositoryUrl>https://github.com/NTDLS/AxisEngine</RepositoryUrl>
		<PackageTags>game-engnie</PackageTags>
		<PackageReleaseNotes>
			Initial release, super alpha.
		</PackageReleaseNotes>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Authors>NetworkDLS</Authors>
		<Company>NetworkDLS</Company>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageIcon>Logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="AeIcon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\Logo.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NTDLS.DatagramMessaging" Version="1.9.0" />
		<PackageReference Include="NTDLS.ReliableMessaging" Version="3.4.0" />
	</ItemGroup>

</Project>
